[build]
  command = "npm install -g @microsoft/rush@5.50.0 && rush update && rush build --to @re-do/documentation"
  publish = "build"
[build.environment]
  NODE_VERSION = "16.8.0"
  NPM_FLAGS = "--help"
