name: pr

on:
    pull_request:
        branches: [main]

defaults:
    run:
        shell: bash

jobs:
    core:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout re-po
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup re-po
              uses: ./.github/actions/setup

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm test

            - name: Bench
              run: pnpm bench

            - name: Website
              run: pnpm build-pages

    compatibility:
        needs: core
        timeout-minutes: 20
        strategy:
            matrix:
                node: [lts/*]
                os: [windows-latest, macos-latest]
                include:
                    - os: ubuntu-latest
                      node: lts/-1
                    - os: ubuntu-latest
                      node: latest

        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout re-po
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup re-po
              uses: ./.github/actions/setup
              with:
                  node: ${{ matrix.node }}

            - name: Test
              run: pnpm test

    pr-checks:
        needs: compatibility
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - run: echo All checks succeeded! ðŸš¢
